#! /usr/bin/env perl

use warnings;
use strict;

use IO::File;

my $left = shift @ARGV or die;
my $leftfh = new IO::File $left, "r" or die;

my %join;

while (defined ($_ = <$leftfh>))
  {
    chomp;
    my ($a, $rest) = split /\s+/, $_, 2;

    $join{$a} = $rest;
  }

while (defined ($_ = <>))
  {
    chomp;
    print "$_ $join{$.-1}\n" if $join{$.-1};
  }

